language: node_js
node_js:
  - 10
install:
  - yarn install
  - yarn build
script: 'true'
deploy:
  provider: s3
  access_key_id: "AKIAVCO44IP6GSPQEP5A"
  secret_access_key: $AWS_SECRET_KEY
  bucket: "recipes.foinse.io"
  skip_cleanup: true
  local_dir: build
